version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pokedb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pokemon-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/pokedex
    volumes:
      - ./backend:/app
    command: ["bun", "dist/index.js"] # Adjust if using ts-node or another start command
    working_dir: /app

  frontend:
    build: ./frontend
    container_name: pokemon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["bun", "run", "dev"]

volumes:
  pgdata:
