services:
  db:
    image: ankane/pgvector:latest
    container_name: pokedb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: . # Build from root to access shared folder
      dockerfile: backend/Dockerfile
    container_name: pokemon-backend
    ports:
      - "3457:3457"
    depends_on:
      - db
      - embedding-service
      - sealed-classifier-service
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/pokedex
      EMBEDDING_SERVICE_URL: http://embedding-service:8000
      SEALED_CLASSIFIER_URL: http://sealed-classifier-service:8000
    volumes:
      # - ./backend:/app/backend # uncomment for VPS but comment for local
      - ./backend/src:/app/backend/src # Mount only src for hot reload; uncomment for local but comment for VPS
      - ./shared/src:/app/shared/src
    working_dir: /app/backend # Sets the default directory that commands will execute from. This is important because the command (like bun run dev) will run relative to this path.
    command: ["bun", "run", "dev"] # overrides the CMD in Dockerfile

  frontend:
    build:
      context: . # Build from root if frontend needs shared resources
      dockerfile: frontend/Dockerfile
    container_name: pokemon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared # Mount shared folder if frontend needs it
      - /app/frontend/node_modules # Prevent overwriting
    working_dir: /app/frontend
    command: ["bun", "run", "dev"]

  embedding-service:
    build:
      context: ./scripts/python/embedding_service
      dockerfile: Dockerfile
    container_name: pokemon-embedding-service
    ports:
      - "8000:8000"
    environment:
      - MODEL_CACHE=/models
    volumes:
      - model-cache:/models

  sealed-classifier-service:
    build:
      context: ./scripts/python/sealed_classifier_service
      dockerfile: Dockerfile
    environment:
      MODEL_NAME: "/app/model"
    container_name: pokemon-sealed-classifier
    ports:
      - "8001:8000"

  # mcp:
  #   build:
  #     context: . # Build from root to access shared folder
  #     dockerfile: mcp/Dockerfile
  #   container_name: pokemon-mcp
  #   ports:
  #     - "3458:3458" # Different port for MCP
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/pokedex
  #   volumes:
  #     - .:/app # Mount entire project
  #   working_dir: /app
  #   command: ["bun", "dist/mcp/src/server.js"]

volumes:
  pgdata:
  model-cache:
