apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemon-ingress
  namespace: pokemon-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - poke-trades.com
    secretName: pokemon-tls
  rules:
  - host: poke-trades.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3457
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80