export const json = {
  count: 4,
  result: [
    {
      skuId: "8121259",
      variant: "Holofoil",
      language: "English",
      condition: "Near Mint",
      averageDailyQuantitySold: "8",
      averageDailyTransactionCount: "8",
      totalQuantitySold: "786",
      totalTransactionCount: "727",
      trendingMarketPricePercentages: {},
      buckets: [
        {
          marketPrice: "60.99",
          quantitySold: "15",
          lowSalePrice: "52",
          lowSalePriceWithShipping: "55",
          highSalePrice: "70.49",
          highSalePriceWithShipping: "70.49",
          transactionCount: "15",
          bucketStartDate: "2025-05-01",
        },
        {
          marketPrice: "59.81",
          quantitySold: "21",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "53.97",
          highSalePrice: "69.77",
          highSalePriceWithShipping: "69.77",
          transactionCount: "21",
          bucketStartDate: "2025-04-28",
        },
        {
          marketPrice: "62.62",
          quantitySold: "14",
          lowSalePrice: "51.27",
          lowSalePriceWithShipping: "56.26",
          highSalePrice: "77.97",
          highSalePriceWithShipping: "77.97",
          transactionCount: "14",
          bucketStartDate: "2025-04-25",
        },
        {
          marketPrice: "64.4",
          quantitySold: "21",
          lowSalePrice: "55",
          lowSalePriceWithShipping: "55.99",
          highSalePrice: "79.99",
          highSalePriceWithShipping: "79.99",
          transactionCount: "20",
          bucketStartDate: "2025-04-22",
        },
        {
          marketPrice: "65.39",
          quantitySold: "30",
          lowSalePrice: "55",
          lowSalePriceWithShipping: "56.45",
          highSalePrice: "105.45",
          highSalePriceWithShipping: "110.44",
          transactionCount: "30",
          bucketStartDate: "2025-04-19",
        },
        {
          marketPrice: "61.44",
          quantitySold: "33",
          lowSalePrice: "56.5",
          lowSalePriceWithShipping: "58.5",
          highSalePrice: "71.97",
          highSalePriceWithShipping: "81.94",
          transactionCount: "31",
          bucketStartDate: "2025-04-16",
        },
        {
          marketPrice: "60.72",
          quantitySold: "21",
          lowSalePrice: "54.01",
          lowSalePriceWithShipping: "58",
          highSalePrice: "63.99",
          highSalePriceWithShipping: "63.99",
          transactionCount: "21",
          bucketStartDate: "2025-04-13",
        },
        {
          marketPrice: "60.45",
          quantitySold: "14",
          lowSalePrice: "57",
          lowSalePriceWithShipping: "57",
          highSalePrice: "69.91",
          highSalePriceWithShipping: "69.91",
          transactionCount: "14",
          bucketStartDate: "2025-04-10",
        },
        {
          marketPrice: "60.68",
          quantitySold: "22",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "54.99",
          highSalePrice: "69.95",
          highSalePriceWithShipping: "69.95",
          transactionCount: "22",
          bucketStartDate: "2025-04-07",
        },
        {
          marketPrice: "62.01",
          quantitySold: "31",
          lowSalePrice: "51",
          lowSalePriceWithShipping: "55.99",
          highSalePrice: "69.95",
          highSalePriceWithShipping: "69.95",
          transactionCount: "31",
          bucketStartDate: "2025-04-04",
        },
        {
          marketPrice: "60.42",
          quantitySold: "16",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "50.99",
          highSalePrice: "70",
          highSalePriceWithShipping: "77.16",
          transactionCount: "16",
          bucketStartDate: "2025-04-01",
        },
        {
          marketPrice: "62.57",
          quantitySold: "18",
          lowSalePrice: "55",
          lowSalePriceWithShipping: "56.26",
          highSalePrice: "79.48",
          highSalePriceWithShipping: "79.48",
          transactionCount: "18",
          bucketStartDate: "2025-03-29",
        },
        {
          marketPrice: "61.9",
          quantitySold: "40",
          lowSalePrice: "54.95",
          lowSalePriceWithShipping: "56.2",
          highSalePrice: "79.45",
          highSalePriceWithShipping: "79.45",
          transactionCount: "20",
          bucketStartDate: "2025-03-26",
        },
        {
          marketPrice: "66.58",
          quantitySold: "17",
          lowSalePrice: "55.99",
          lowSalePriceWithShipping: "58.99",
          highSalePrice: "88.83",
          highSalePriceWithShipping: "88.83",
          transactionCount: "17",
          bucketStartDate: "2025-03-23",
        },
        {
          marketPrice: "61.45",
          quantitySold: "35",
          lowSalePrice: "47.26",
          lowSalePriceWithShipping: "48.25",
          highSalePrice: "79.97",
          highSalePriceWithShipping: "79.97",
          transactionCount: "34",
          bucketStartDate: "2025-03-20",
        },
        {
          marketPrice: "62.96",
          quantitySold: "17",
          lowSalePrice: "58",
          lowSalePriceWithShipping: "59.5",
          highSalePrice: "75.61",
          highSalePriceWithShipping: "75.61",
          transactionCount: "17",
          bucketStartDate: "2025-03-17",
        },
        {
          marketPrice: "65.24",
          quantitySold: "31",
          lowSalePrice: "59.78",
          lowSalePriceWithShipping: "60.77",
          highSalePrice: "79.49",
          highSalePriceWithShipping: "79.49",
          transactionCount: "26",
          bucketStartDate: "2025-03-14",
        },
        {
          marketPrice: "65.27",
          quantitySold: "14",
          lowSalePrice: "62",
          lowSalePriceWithShipping: "62.99",
          highSalePrice: "79.74",
          highSalePriceWithShipping: "79.74",
          transactionCount: "14",
          bucketStartDate: "2025-03-11",
        },
        {
          marketPrice: "66.18",
          quantitySold: "17",
          lowSalePrice: "58",
          lowSalePriceWithShipping: "60",
          highSalePrice: "79.97",
          highSalePriceWithShipping: "79.97",
          transactionCount: "17",
          bucketStartDate: "2025-03-08",
        },
        {
          marketPrice: "69.46",
          quantitySold: "41",
          lowSalePrice: "58",
          lowSalePriceWithShipping: "60.99",
          highSalePrice: "79.95",
          highSalePriceWithShipping: "79.95",
          transactionCount: "35",
          bucketStartDate: "2025-03-05",
        },
        {
          marketPrice: "71.98",
          quantitySold: "28",
          lowSalePrice: "60.55",
          lowSalePriceWithShipping: "61.54",
          highSalePrice: "79.9",
          highSalePriceWithShipping: "79.9",
          transactionCount: "28",
          bucketStartDate: "2025-03-02",
        },
        {
          marketPrice: "73.02",
          quantitySold: "17",
          lowSalePrice: "64.27",
          lowSalePriceWithShipping: "67.02",
          highSalePrice: "113.75",
          highSalePriceWithShipping: "113.75",
          transactionCount: "17",
          bucketStartDate: "2025-02-27",
        },
        {
          marketPrice: "67.15",
          quantitySold: "41",
          lowSalePrice: "60",
          lowSalePriceWithShipping: "63.27",
          highSalePrice: "80.99",
          highSalePriceWithShipping: "82.43",
          transactionCount: "38",
          bucketStartDate: "2025-02-24",
        },
        {
          marketPrice: "70.66",
          quantitySold: "32",
          lowSalePrice: "63.95",
          lowSalePriceWithShipping: "65.99",
          highSalePrice: "79.99",
          highSalePriceWithShipping: "79.99",
          transactionCount: "32",
          bucketStartDate: "2025-02-21",
        },
        {
          marketPrice: "72.37",
          quantitySold: "39",
          lowSalePrice: "67.99",
          lowSalePriceWithShipping: "69.73",
          highSalePrice: "79.99",
          highSalePriceWithShipping: "79.99",
          transactionCount: "36",
          bucketStartDate: "2025-02-18",
        },
        {
          marketPrice: "70.77",
          quantitySold: "31",
          lowSalePrice: "64.95",
          lowSalePriceWithShipping: "66.24",
          highSalePrice: "82.65",
          highSalePriceWithShipping: "82.65",
          transactionCount: "31",
          bucketStartDate: "2025-02-15",
        },
        {
          marketPrice: "69.54",
          quantitySold: "42",
          lowSalePrice: "60.89",
          lowSalePriceWithShipping: "65.88",
          highSalePrice: "88.38",
          highSalePriceWithShipping: "88.38",
          transactionCount: "37",
          bucketStartDate: "2025-02-12",
        },
        {
          marketPrice: "77.33",
          quantitySold: "30",
          lowSalePrice: "45.02",
          lowSalePriceWithShipping: "46.01",
          highSalePrice: "83.15",
          highSalePriceWithShipping: "83.15",
          transactionCount: "17",
          bucketStartDate: "2025-02-09",
        },
        {
          marketPrice: "80.35",
          quantitySold: "19",
          lowSalePrice: "74",
          lowSalePriceWithShipping: "74.5",
          highSalePrice: "88.83",
          highSalePriceWithShipping: "88.83",
          transactionCount: "19",
          bucketStartDate: "2025-02-06",
        },
        {
          marketPrice: "80.03",
          quantitySold: "21",
          lowSalePrice: "72",
          lowSalePriceWithShipping: "73.49",
          highSalePrice: "89.93",
          highSalePriceWithShipping: "89.93",
          transactionCount: "21",
          bucketStartDate: "2025-02-03",
        },
      ],
    },
    {
      skuId: "8121260",
      variant: "Holofoil",
      language: "English",
      condition: "Lightly Played",
      averageDailyQuantitySold: "0",
      averageDailyTransactionCount: "0",
      totalQuantitySold: "86",
      totalTransactionCount: "85",
      trendingMarketPricePercentages: {},
      buckets: [
        {
          marketPrice: "54.88",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-05-02",
        },
        {
          marketPrice: "54.88",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-29",
        },
        {
          marketPrice: "54.88",
          quantitySold: "3",
          lowSalePrice: "54.82",
          lowSalePriceWithShipping: "56.31",
          highSalePrice: "58",
          highSalePriceWithShipping: "58",
          transactionCount: "3",
          bucketStartDate: "2025-04-26",
        },
        {
          marketPrice: "55.03",
          quantitySold: "2",
          lowSalePrice: "49.85",
          lowSalePriceWithShipping: "53",
          highSalePrice: "53",
          highSalePriceWithShipping: "53.99",
          transactionCount: "2",
          bucketStartDate: "2025-04-23",
        },
        {
          marketPrice: "55.78",
          quantitySold: "2",
          lowSalePrice: "56.13",
          lowSalePriceWithShipping: "56.13",
          highSalePrice: "56.15",
          highSalePriceWithShipping: "56.15",
          transactionCount: "2",
          bucketStartDate: "2025-04-20",
        },
        {
          marketPrice: "56.09",
          quantitySold: "2",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "54.5",
          highSalePrice: "56",
          highSalePriceWithShipping: "56",
          transactionCount: "2",
          bucketStartDate: "2025-04-17",
        },
        {
          marketPrice: "56.5",
          quantitySold: "3",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "54.5",
          highSalePrice: "54.99",
          highSalePriceWithShipping: "54.99",
          transactionCount: "3",
          bucketStartDate: "2025-04-14",
        },
        {
          marketPrice: "57",
          quantitySold: "2",
          lowSalePrice: "54.99",
          lowSalePriceWithShipping: "54.99",
          highSalePrice: "60.74",
          highSalePriceWithShipping: "60.74",
          transactionCount: "2",
          bucketStartDate: "2025-04-11",
        },
        {
          marketPrice: "57.13",
          quantitySold: "2",
          lowSalePrice: "57.49",
          lowSalePriceWithShipping: "59.48",
          highSalePrice: "58.49",
          highSalePriceWithShipping: "67.99",
          transactionCount: "2",
          bucketStartDate: "2025-04-08",
        },
        {
          marketPrice: "57.71",
          quantitySold: "2",
          lowSalePrice: "57.39",
          lowSalePriceWithShipping: "57.99",
          highSalePrice: "57.99",
          highSalePriceWithShipping: "58.37",
          transactionCount: "2",
          bucketStartDate: "2025-04-05",
        },
        {
          marketPrice: "58.33",
          quantitySold: "6",
          lowSalePrice: "54.5",
          lowSalePriceWithShipping: "55",
          highSalePrice: "55.49",
          highSalePriceWithShipping: "59.49",
          transactionCount: "6",
          bucketStartDate: "2025-04-02",
        },
        {
          marketPrice: "60.12",
          quantitySold: "3",
          lowSalePrice: "51.22",
          lowSalePriceWithShipping: "51.22",
          highSalePrice: "56",
          highSalePriceWithShipping: "56",
          transactionCount: "3",
          bucketStartDate: "2025-03-30",
        },
        {
          marketPrice: "60.74",
          quantitySold: "1",
          lowSalePrice: "55",
          lowSalePriceWithShipping: "55",
          highSalePrice: "55",
          highSalePriceWithShipping: "55",
          transactionCount: "1",
          bucketStartDate: "2025-03-27",
        },
        {
          marketPrice: "61.08",
          quantitySold: "5",
          lowSalePrice: "61.04",
          lowSalePriceWithShipping: "61.95",
          highSalePrice: "61.95",
          highSalePriceWithShipping: "62.29",
          transactionCount: "4",
          bucketStartDate: "2025-03-24",
        },
        {
          marketPrice: "61.3",
          quantitySold: "3",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "50.99",
          highSalePrice: "58",
          highSalePriceWithShipping: "59.99",
          transactionCount: "3",
          bucketStartDate: "2025-03-21",
        },
        {
          marketPrice: "63.04",
          quantitySold: "3",
          lowSalePrice: "57.67",
          lowSalePriceWithShipping: "58.98",
          highSalePrice: "58.99",
          highSalePriceWithShipping: "59.55",
          transactionCount: "3",
          bucketStartDate: "2025-03-18",
        },
        {
          marketPrice: "63.71",
          quantitySold: "2",
          lowSalePrice: "62.93",
          lowSalePriceWithShipping: "62.93",
          highSalePrice: "63.64",
          highSalePriceWithShipping: "63.64",
          transactionCount: "2",
          bucketStartDate: "2025-03-15",
        },
        {
          marketPrice: "63.56",
          quantitySold: "5",
          lowSalePrice: "60.4",
          lowSalePriceWithShipping: "61.39",
          highSalePrice: "63.48",
          highSalePriceWithShipping: "63.48",
          transactionCount: "5",
          bucketStartDate: "2025-03-12",
        },
        {
          marketPrice: "63.74",
          quantitySold: "2",
          lowSalePrice: "60",
          lowSalePriceWithShipping: "61",
          highSalePrice: "63.84",
          highSalePriceWithShipping: "63.84",
          transactionCount: "2",
          bucketStartDate: "2025-03-09",
        },
        {
          marketPrice: "64.04",
          quantitySold: "3",
          lowSalePrice: "60",
          lowSalePriceWithShipping: "60.99",
          highSalePrice: "64.17",
          highSalePriceWithShipping: "64.17",
          transactionCount: "3",
          bucketStartDate: "2025-03-06",
        },
        {
          marketPrice: "64.38",
          quantitySold: "7",
          lowSalePrice: "58.84",
          lowSalePriceWithShipping: "59.83",
          highSalePrice: "63.99",
          highSalePriceWithShipping: "63.99",
          transactionCount: "7",
          bucketStartDate: "2025-03-03",
        },
        {
          marketPrice: "66.91",
          quantitySold: "2",
          lowSalePrice: "64.94",
          lowSalePriceWithShipping: "64.94",
          highSalePrice: "77.94",
          highSalePriceWithShipping: "97.93",
          transactionCount: "2",
          bucketStartDate: "2025-02-28",
        },
        {
          marketPrice: "67.38",
          quantitySold: "2",
          lowSalePrice: "64.95",
          lowSalePriceWithShipping: "64.95",
          highSalePrice: "72.7",
          highSalePriceWithShipping: "72.7",
          transactionCount: "2",
          bucketStartDate: "2025-02-25",
        },
        {
          marketPrice: "67.41",
          quantitySold: "1",
          lowSalePrice: "64",
          lowSalePriceWithShipping: "64.99",
          highSalePrice: "64",
          highSalePriceWithShipping: "64.99",
          transactionCount: "1",
          bucketStartDate: "2025-02-22",
        },
        {
          marketPrice: "68.97",
          quantitySold: "5",
          lowSalePrice: "59.99",
          lowSalePriceWithShipping: "59.99",
          highSalePrice: "62.95",
          highSalePriceWithShipping: "62.95",
          transactionCount: "5",
          bucketStartDate: "2025-02-19",
        },
        {
          marketPrice: "70.5",
          quantitySold: "7",
          lowSalePrice: "59.99",
          lowSalePriceWithShipping: "59.99",
          highSalePrice: "70.56",
          highSalePriceWithShipping: "71.55",
          transactionCount: "7",
          bucketStartDate: "2025-02-16",
        },
        {
          marketPrice: "72.49",
          quantitySold: "2",
          lowSalePrice: "65",
          lowSalePriceWithShipping: "65",
          highSalePrice: "65",
          highSalePriceWithShipping: "65",
          transactionCount: "2",
          bucketStartDate: "2025-02-13",
        },
        {
          marketPrice: "72.7",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-10",
        },
        {
          marketPrice: "72.62",
          quantitySold: "1",
          lowSalePrice: "70",
          lowSalePriceWithShipping: "74.5",
          highSalePrice: "70",
          highSalePriceWithShipping: "74.5",
          transactionCount: "1",
          bucketStartDate: "2025-02-07",
        },
        {
          marketPrice: "71.54",
          quantitySold: "8",
          lowSalePrice: "71",
          lowSalePriceWithShipping: "71.78",
          highSalePrice: "77.49",
          highSalePriceWithShipping: "77.49",
          transactionCount: "8",
          bucketStartDate: "2025-02-04",
        },
      ],
    },
    {
      skuId: "8121261",
      variant: "Holofoil",
      language: "English",
      condition: "Moderately Played",
      averageDailyQuantitySold: "0",
      averageDailyTransactionCount: "0",
      totalQuantitySold: "7",
      totalTransactionCount: "7",
      trendingMarketPricePercentages: {},
      buckets: [
        {
          marketPrice: "46.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-05-01",
        },
        {
          marketPrice: "45.77",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-28",
        },
        {
          marketPrice: "45.77",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-25",
        },
        {
          marketPrice: "45.77",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-22",
        },
        {
          marketPrice: "45.58",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-19",
        },
        {
          marketPrice: "45.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-16",
        },
        {
          marketPrice: "45.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-13",
        },
        {
          marketPrice: "45.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-10",
        },
        {
          marketPrice: "45.1",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-07",
        },
        {
          marketPrice: "44.6",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-04",
        },
        {
          marketPrice: "44.44",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-01",
        },
        {
          marketPrice: "43.81",
          quantitySold: "2",
          lowSalePrice: "49.99",
          lowSalePriceWithShipping: "50.98",
          highSalePrice: "54.99",
          highSalePriceWithShipping: "58.98",
          transactionCount: "2",
          bucketStartDate: "2025-03-29",
        },
        {
          marketPrice: "43.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-26",
        },
        {
          marketPrice: "43.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-23",
        },
        {
          marketPrice: "43.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-20",
        },
        {
          marketPrice: "43.49",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-17",
        },
        {
          marketPrice: "43.35",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-14",
        },
        {
          marketPrice: "43.08",
          quantitySold: "1",
          lowSalePrice: "60",
          lowSalePriceWithShipping: "60",
          highSalePrice: "60",
          highSalePriceWithShipping: "60",
          transactionCount: "1",
          bucketStartDate: "2025-03-11",
        },
        {
          marketPrice: "42.08",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-08",
        },
        {
          marketPrice: "41.75",
          quantitySold: "1",
          lowSalePrice: "50",
          lowSalePriceWithShipping: "53.99",
          highSalePrice: "50",
          highSalePriceWithShipping: "53.99",
          transactionCount: "1",
          bucketStartDate: "2025-03-05",
        },
        {
          marketPrice: "41.58",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-02",
        },
        {
          marketPrice: "41.58",
          quantitySold: "1",
          lowSalePrice: "73.49",
          lowSalePriceWithShipping: "73.49",
          highSalePrice: "73.49",
          highSalePriceWithShipping: "73.49",
          transactionCount: "1",
          bucketStartDate: "2025-02-27",
        },
        {
          marketPrice: "39.46",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-24",
        },
        {
          marketPrice: "39.46",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-21",
        },
        {
          marketPrice: "39.46",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-18",
        },
        {
          marketPrice: "39.46",
          quantitySold: "1",
          lowSalePrice: "70",
          lowSalePriceWithShipping: "70",
          highSalePrice: "70",
          highSalePriceWithShipping: "70",
          transactionCount: "1",
          bucketStartDate: "2025-02-15",
        },
        {
          marketPrice: "37.28",
          quantitySold: "1",
          lowSalePrice: "37.27",
          lowSalePriceWithShipping: "37.27",
          highSalePrice: "37.27",
          highSalePriceWithShipping: "37.27",
          transactionCount: "1",
          bucketStartDate: "2025-02-12",
        },
        {
          marketPrice: "37.28",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-09",
        },
        {
          marketPrice: "37.28",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-06",
        },
        {
          marketPrice: "37.28",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-03",
        },
      ],
    },
    {
      skuId: "8121263",
      variant: "Holofoil",
      language: "English",
      condition: "Damaged",
      averageDailyQuantitySold: "0",
      averageDailyTransactionCount: "0",
      totalQuantitySold: "2",
      totalTransactionCount: "2",
      trendingMarketPricePercentages: {},
      buckets: [
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-05-03",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-30",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-27",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-24",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-21",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-18",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-15",
        },
        {
          marketPrice: "35.32",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-12",
        },
        {
          marketPrice: "34.39",
          quantitySold: "1",
          lowSalePrice: "41.99",
          lowSalePriceWithShipping: "41.99",
          highSalePrice: "41.99",
          highSalePriceWithShipping: "41.99",
          transactionCount: "1",
          bucketStartDate: "2025-04-09",
        },
        {
          marketPrice: "33.44",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-04-06",
        },
        {
          marketPrice: "32.73",
          quantitySold: "1",
          lowSalePrice: "42",
          lowSalePriceWithShipping: "42",
          highSalePrice: "42",
          highSalePriceWithShipping: "42",
          transactionCount: "1",
          bucketStartDate: "2025-04-03",
        },
        {
          marketPrice: "31.3",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-31",
        },
        {
          marketPrice: "30.9",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-28",
        },
        {
          marketPrice: "30.9",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-25",
        },
        {
          marketPrice: "30.91",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-22",
        },
        {
          marketPrice: "30.92",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-19",
        },
        {
          marketPrice: "30.92",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-16",
        },
        {
          marketPrice: "31.11",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-13",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-10",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-07",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-04",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-03-01",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-26",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-23",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-20",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-17",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-14",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-11",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-08",
        },
        {
          marketPrice: "31.5",
          quantitySold: "0",
          lowSalePrice: "0",
          lowSalePriceWithShipping: "0",
          highSalePrice: "0",
          highSalePriceWithShipping: "0",
          transactionCount: "0",
          bucketStartDate: "2025-02-05",
        },
      ],
    },
  ],
};
