export const sealedProductNames = [
  "Sword and Shield Base Booster Box",
  "Sword and Shield base Elite Trainer Box set",
  "Rebel Clash Booster Box",
  "Rebel Clash Elite Trainer Box",
  "Darkness Ablaze Booster Box",
  "Darkness Ablaze Elite Trainer Box",
  "Champions Path Elite Trainer Box",
  "Vivid Voltage Booster Box",
  "Vivid Voltage Elite Trainer Box",
  "Shining Fates Elite Trainer Box",
  "Battle Styles Booster Box",
  "Battle Styles Elite Trainer Box Set",
  "Chilling Reign Booster Box",
  "Chilling Reign Elite Trainer Box Set -center",
  "Chilling Reign Pokemon Center Elite Trainer Box Set",
  "Evolving Skies Booster Box",
  "Evolving Skies Elite Trainer Box Set -center",
  "Evolving Skies Pokemon Center Elite Trainer Box Set",
  "Fusion Strike Booster Box",
  "Fusion Strike Elite Trainer Box -center",
  "Fusion Strike Pokemon Center Elite Trainer Box",
  "Celebrations Elite Trainer Box -center",
  "Celebrations Pokemon Center Elite Trainer Box",
  "Brilliant Stars Booster Box",
  "Brilliant Stars Elite Trainer Box -center",
  "Brilliant Stars Pokemon Center Elite Trainer Box",
  "Astral Radiance Booster Box",
  "Astral Radiance Elite Trainer Box -center",
  "Astral Radiance Pokemon Center Elite Trainer Box",
  "Pokemon Go Elite Trainer Box -center",
  "Pokemon Go Pokemon Center Elite Trainer Box",
  "Lost Origin Booster Box",
  "Lost Origin Elite Trainer Box -center",
  "Lost Origin Pokemon Center Elite Trainer Box",
  "Silver Tempest Booster Box",
  "Silver Tempest Elite Trainer Box -center",
  "Silver Tempest Pokemon Center Elite Trainer Box",
  "Crown Zenith Elite Trainer Box -center",
  "Crown Zenith Pokemon Center Elite Trainer Box",
  "Scarlet Violet Base Booster Box",
  "Scarlet Violet Base Elite Trainer Box Set -center",
  "Scarlet Violet Base Pokemon Center Elite Trainer Box Set",
  "Paldea Evolved Booster Box",
  "Paldea Evolved Elite Trainer Box -center",
  "Paldea Evolved Pokemon Center Elite Trainer Box",
  "Obsidian Flames Booster Box",
  "Obsidian Flames Elite Trainer Box -center",
  "Obsidian Flames Pokemon Center Elite Trainer Box",
  "151 Elite Trainer Box -center",
  "151 Pokemon Center Elite Trainer Box",
  "Paradox Rift Booster Box",
  "Paradox Rift Elite Trainer Box -center",
  "Paradox Rift Pokemon Center Elite Trainer Box",
  "Paldean Fates Elite Trainer Box -center",
  "Paldean Fates Pokemon Center Elite Trainer Box",
  "Temporal Forces Booster Box",
  "Temporal Forces Elite Trainer Box Set -center",
  "Temporal Forces Pokemon Center Elite Trainer Box Set",
  "Twilight Masquerade Booster Box",
  "Twilight Masquerade Elite Trainer Box -center",
  "Twilight Masquerade Pokemon Center Elite Trainer Box",
  "Shrouded Fable Elite Trainer Box -center",
  "Shrouded Fable Pokemon Center Elite Trainer Box",
  "Stellar Crown Booster Box",
  "Stellar Crown Elite Trainer Box -center",
  "Stellar Crown Pokemon Center Elite Trainer Box",
  "Surging Sparks Booster Box",
  "Surging Sparks Elite Trainer Box -center",
  "Surging Sparks Elite Pokemon Center Trainer Box",
  "Prismatic Evolutions Elite Trainer Box -center",
  "Prismatic Evolutions Pokemon Center Elite Trainer Box",
  "Destined Rivals Booster Box",
  "Destined Rivals Elite Trainer Box -center",
  "Destined Rivals Pokemon Center Elite Trainer Box",
  "Black Bolt Elite Trainer Box -center",
  "Black Bolt Pokemon Center Elite Trainer Box",
  "White Flare Elite Trainer Box -center",
  "White Flare Pokemon Center Elite Trainer Box",
  "Mega Evolution base Booster Box",
  "Mega Evolution base Elite Trainer Box -center",
  "Mega Evolution base Pokemon Center Elite Trainer Box",
  "Phantasmal Flames Booster Box",
  "Phantasmal Flames Elite Trainer Box -center",
  "Phantasmal Flames Pokemon Center Elite Trainer Box",
];
